In [3]:
import torch
print(torch.__version__)

2.9.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available.Using CPU")

GPU not available.Using CPU


# 1. Creating Tensors:


In [ ]:
#using empty
a=torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
b=torch.rand(2,3)

In [ ]:
b.shape

torch.Size([2, 3])

The line torch.rand(2,3) creates a PyTorch tensor (which is similar to a multi-dimensional array) with random numbers.

torch.rand(): This is the function that generates random numbers.
(2,3): These are the dimensions of the tensor. It means the tensor will have 2 rows and 3 columns. The numbers generated will be uniformly distributed between 0 and 1.

In [ ]:
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

#arange
print("using arange->",torch.arange(0,10,2))

#using linspace
print("using linespace->",torch.linspace(0,10,20))

#using eye
print("using eye->",torch.eye(5))

#using full
print("using full->", torch.full((3,3),5))

using arange-> tensor([0, 2, 4, 6, 8])
using linespace-> tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])
using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])




```
1. torch.arange()

torch.arange() creates a 1-D tensor with evenly spaced values within a given range.

Syntax:

torch.arange(start, end, step)


start → starting value (inclusive)

end → ending value (exclusive)

step → gap between consecutive values

Example:

torch.arange(0, 10, 2)


Output:

tensor([0, 2, 4, 6, 8])


Explanation:

Starts from 0

Stops before 10

Increments by 2

This is similar to Python’s range() but returns a tensor instead of a list.

2. torch.linspace()

torch.linspace() creates a 1-D tensor with a fixed number of equally spaced values between two numbers.

Syntax:

torch.linspace(start, end, steps)


start → starting value

end → ending value (included)

steps → total number of values to generate

Example:

torch.linspace(0, 10, 20)


Output:

tensor([ 0.0000, 0.5263, 1.0526, ..., 9.4737, 10.0000 ])


Explanation:

Generates 20 values

Values are evenly spaced

Both 0 and 10 are included

This is very useful in numerical analysis and plotting.

3. torch.eye()

torch.eye() creates an identity matrix, where:

Diagonal elements are 1

All other elements are 0

Syntax:

torch.eye(n)


n → number of rows and columns

Example:

torch.eye(5)


Output:

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


Explanation:

Creates a 5 × 5 identity matrix

Commonly used in linear algebra and neural networks

4. torch.full()

torch.full() creates a tensor of a given shape where all elements have the same value.

Syntax:

torch.full(size, fill_value)


size → shape of the tensor

fill_value → value to fill in every position

Example:

torch.full((3, 3), 5)


Output:

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Explanation:

Creates a 3 × 3 tensor

Every element is 5

Useful for initialization and testing models.

Summary Table
Function	Purpose
torch.arange()	Sequence with fixed step size
torch.linspace()	Fixed number of evenly spaced values
torch.eye()	Identity matrix
torch.full()	Tensor filled with one constant value
```



# 2. Finding Tensor Shape:

In [ ]:
x=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x.shape

torch.Size([2, 3, 3])

In [ ]:
#making empty tensor with the same shape as x
torch.empty_like(x)

tensor([[[7364905161442014002, 8243121639892462626, 2459029315949257070],
         [7308604897285731189, 8319104481851616290, 3972773255352053609],
         [3270229478590538041, 7219609046422282853, 3543550261546528048]],

        [[4049642309034391139, 7863883273267000624, 2478510836883089267],
         [7813865678659788858, 8462656716707034213, 8512401619612365669],
         [4189032028197581413, 2318265498517971488, 2322206377002492962]]])

In [ ]:
#making tensor with zeros the same shape as x
torch.zeros_like(x)

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [ ]:
#making tensor with ones the same shape as x
torch.ones_like(x)

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

In [ ]:
# x has integer values whereas rand function assigns float values so the basic cpode here won't work. we need to specify the datatype
# torch.rand_like(x) -> this line would give the error
torch.rand_like(x,dtype=torch.float32)

tensor([[[0.2239, 0.3023, 0.1784],
         [0.8238, 0.5557, 0.9770],
         [0.4440, 0.9478, 0.7445]],

        [[0.4892, 0.2426, 0.7003],
         [0.5277, 0.2472, 0.7909],
         [0.4235, 0.0169, 0.2209]]])

# 3.Tensor DataTypes:

In [ ]:
#find data type
x.dtype

torch.int64

In [ ]:
#assigning data type to a tensor
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# 3. Mathematical Operations in Tensors:

## A. Scalar Operation:

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.5207, 0.5983],
        [0.5849, 0.3019]])

In [ ]:
#addition
x+2

#substraction
x-2

#multiplication
x*3

#division
x/3

#int division
(x*100)//3

#mod
((x*100)//3)%2

#power
x**2

tensor([[0.2712, 0.3580],
        [0.3421, 0.0912]])

## B. Element wise operation:

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.1762, 0.0739, 0.2950],
        [0.4179, 0.9942, 0.0601]])
tensor([[0.9236, 0.8855, 0.2479],
        [0.5959, 0.7125, 0.3741]])


In [ ]:
#add
a+b

#sub
a-b

#multiply:
a*b

#division:
a/b

#power
a**b

#mod
a%b


tensor([[0.1762, 0.0739, 0.0472],
        [0.4179, 0.2816, 0.0601]])

In [ ]:
c= torch.tensor([1,-2,3,-4])

In [ ]:
#abs:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp-> puts values in the tensor into a single range
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## C. Reduction Operation:

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10)
e

tensor([[1, 7, 5],
        [7, 7, 3]])

This line of code creates a 2-D tensor filled with random integers using PyTorch.

1. torch.randint()
torch.randint() is used to generate random integer values in a tensor.
General syntax:
torch.randint(low, high, size)

2. size=(2, 3)
Specifies the shape of the tensor
Creates a tensor with
2 rows
3 columns
So the output tensor will be a 2 × 3 matrix.

3. low=0
The minimum value that can appear in the tensor
0 is included

4. high=10
The maximum limit for values
10 is excluded

So values will be in the range:
0 ≤ value < 10
i.e., from 0 to 9

In [ ]:
#sum-> sums up all the numbers
torch.sum(e)

#sum along columns
torch.sum(e,dim=0)

#sum along rows
torch.sum(e,dim=1)


tensor([13, 17])

In [ ]:
#mean-> works only for float type numbers
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
print(e)

#mean
torch.mean(e)

#mean along columns
torch.mean(e,dim=0)

#mean along rows
torch.mean(e,dim=1)

tensor([[9., 5., 4.],
        [3., 3., 5.]])


tensor([6.0000, 3.6667])

In [ ]:
#median
torch.median(e)

tensor(4.)

In [ ]:
#max and min
torch.max(e)
torch.min(e)

tensor(3.)

In [ ]:
#product:
torch.prod(e)

tensor(8100.)

In [ ]:
#standard deviation
torch.std(e)

tensor(2.2286)

In [ ]:
#variance
torch.var(e)

tensor(4.9667)

In [ ]:
#argmax->gives position of the max element
torch.argmax(e)

tensor(0)

In [ ]:
#argmin->gives position of the min element
torch.argmin(e)

tensor(3)

## D. Matrix Operation:

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[9, 0, 5],
        [3, 5, 0]])
tensor([[5, 8],
        [6, 5],
        [4, 7]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[ 65, 107],
        [ 45,  49]])

In [ ]:
#vectors:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [ ]:
#dot product:
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose:
torch.transpose(f,0,1)

tensor([[9, 3],
        [0, 5],
        [5, 0]])

f

f is a tensor (usually 2-D, but can also be higher-dimensional)

Example:

f = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])


Shape of f:

torch.Size([2, 3])

2. 0

Refers to the first dimension (rows)

3. 1

Refers to the second dimension (columns)

4. torch.transpose(f, 0, 1)

Swaps dimension 0 and dimension 1

Example with Output
f = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

t = torch.transpose(f, 0, 1)
print(t)


Output:

tensor([[1, 4],
        [2, 5],
        [3, 6]])

Shape Change

Before transpose:

f.shape → torch.Size([2, 3])


After transpose:

t.shape → torch.Size([3, 2])

Important Notes

torch.transpose() does not change the original tensor

It returns a new view with swapped dimensions

Works for any dimensional tensor, not just 2-D

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[1., 3., 9.],
        [9., 5., 3.],
        [4., 0., 4.]])

In [ ]:
#determinant:
torch.det(h)

tensor(-232.)

In [ ]:
#inverse->only valid for square matrix
torch.inverse(h)

tensor([[-0.0862,  0.0517,  0.1552],
        [ 0.1034,  0.1379, -0.3362],
        [ 0.0862, -0.0517,  0.0948]])

## E. Comparisson Operation:

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[2, 5, 2],
        [8, 9, 9]])
tensor([[2, 6, 6],
        [9, 1, 5]])


In [ ]:
#greater than:
i>j

#less than:
i<j

#equal to:
i==j

#not equal to
i!=j

#greater than equal to
i>=j

#less than equal to
i<=j

tensor([[ True,  True,  True],
        [ True, False, False]])

## F. Special Functions:

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10)
k

tensor([[3, 9, 7],
        [1, 7, 8]])

In [ ]:
#log
torch.log(k)

tensor([[1.0986, 2.1972, 1.9459],
        [0.0000, 1.9459, 2.0794]])

In [ ]:
#exponent
torch.exp(k)

tensor([[2.0086e+01, 8.1031e+03, 1.0966e+03],
        [2.7183e+00, 1.0966e+03, 2.9810e+03]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[1.7321, 3.0000, 2.6458],
        [1.0000, 2.6458, 2.8284]])

In [ ]:
#sigmoid:
torch.sigmoid(k)

tensor([[0.9526, 0.9999, 0.9991],
        [0.7311, 0.9991, 0.9997]])

In [ ]:
#softmax
# torch.softmax(k,dim=0) -> this would give error as softmax needs the datatype to be float
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

torch.softmax(k,dim=0)

tensor([[0.5000, 0.9526, 0.9975],
        [0.5000, 0.0474, 0.0025]])

Softmax is a function used in machine learning to turn a model’s raw output numbers (called scores or logits) into probabilities that are easy for humans and computers to understand. A neural network may output values like [2, 1, 0], but these numbers do not directly tell us how likely each class is. Softmax fixes this by converting them into values between 0 and 1 that add up to 1, such as [0.66, 0.24, 0.10], so we can say one class is more likely than the others. Mathematically, for an input vector
𝑧
=
[
𝑧
1
,
𝑧
2
,
…
,
𝑧
𝑛
]
z=[z
1
	​

,z
2
	​

,…,z
n
	​

], softmax is defined as

softmax
(
𝑧
𝑖
)
=
𝑒
𝑧
𝑖
∑
𝑗
=
1
𝑛
𝑒
𝑧
𝑗
softmax(z
i
	​

)=
∑
j=1
n
	​

e
z
j
	​

e
z
i
	​

	​


which means each score is exponentiated and then divided by the sum of all exponentiated scores. This process makes larger values stand out more while shrinking smaller ones. Softmax is mainly used in the output layer of multi-class classification models, such as digit recognition or image classification, where only one class can be correct. Its importance comes from the fact that it produces meaningful probabilities, helps the model choose the most likely class, and works smoothly with training methods like cross-entropy loss, making learning stable and effective.

```
# This is formatted as code
```



In [ ]:
#relu
torch.relu(k)

tensor([[2., 4., 6.],
        [2., 1., 0.]])

## F. Inplace Operation:

to perform an inplace operation, just add underscore('_') after the operation name, so now it becomes a relu operation.

In [3]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.3834, 0.3328, 0.9316],
        [0.6333, 0.9779, 0.4166]])
tensor([[0.2058, 0.6594, 0.2479],
        [0.2271, 0.1112, 0.2821]])


In [4]:
m+n

tensor([[0.5892, 0.9922, 1.1795],
        [0.8604, 1.0890, 0.6987]])

In [5]:
# when we perform operations in tensors, usually a new tensor is created everytime, which is not always desirable as it occupies memeory, so inplace operations help us to change the same tensor hence, no new memory allocated
m.add_(n)

tensor([[0.5892, 0.9922, 1.1795],
        [0.8604, 1.0890, 0.6987]])

In [6]:
m

tensor([[0.5892, 0.9922, 1.1795],
        [0.8604, 1.0890, 0.6987]])

In [7]:
n

tensor([[0.2058, 0.6594, 0.2479],
        [0.2271, 0.1112, 0.2821]])

In [8]:
torch.relu(m) # makes no changes in m, craetes new tensor and allocates memory to it

tensor([[0.5892, 0.9922, 1.1795],
        [0.8604, 1.0890, 0.6987]])

In [10]:
m.relu_() # permanent chnages in m

tensor([[0.5892, 0.9922, 1.1795],
        [0.8604, 1.0890, 0.6987]])

## G. Copying Tensors:

In [11]:
a=torch.rand(2,3)
a

tensor([[0.4637, 0.2828, 0.2893],
        [0.6710, 0.9723, 0.2976]])

In [13]:
b=a

In [14]:
b

tensor([[0.4637, 0.2828, 0.2893],
        [0.6710, 0.9723, 0.2976]])

In [15]:
a[0][0]=0

In [16]:
a

tensor([[0.0000, 0.2828, 0.2893],
        [0.6710, 0.9723, 0.2976]])

In [18]:
b # we made changes in a, same change happens in b as well, which is not desirable.

tensor([[0.0000, 0.2828, 0.2893],
        [0.6710, 0.9723, 0.2976]])

In [19]:
# when we use the assignment operator, we donot create a new tensor in the memory but instead, we point a new refernce to the tensor a

In [20]:
#we prove it with id():
id(a)

132519102625536

In [21]:
id(b)

132519102625536

In [22]:
# so for copying we use the clone() function:
b=a.clone()

In [26]:
a

tensor([[0.0000, 0.2828, 0.2893],
        [0.6710, 0.9723, 0.2976]])

In [23]:
b

tensor([[0.0000, 0.2828, 0.2893],
        [0.6710, 0.9723, 0.2976]])

In [24]:
id(a)

132519102625536

In [25]:
id(b)

132518157469728

# Tensor Operations on GPU:

In [3]:
#line to check if the GPU is available
torch.cuda.is_available()

True

In [6]:
device=torch.device('cuda')

In [8]:
torch.rand((2,3), device=device)

tensor([[0.6236, 0.9849, 0.6436],
        [0.9374, 0.8937, 0.8308]], device='cuda:0')

In [10]:
#moving an existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.3853, 0.4599, 0.5322],
        [0.2147, 0.3548, 0.5586]])

In [11]:
b=a.to(device) # converting b to a gpu

In [12]:
b+5

tensor([[5.3853, 5.4599, 5.5322],
        [5.2147, 5.3548, 5.5586]], device='cuda:0')

# Reshaping Tensor:

In [4]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [6]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
b=torch.rand(2,3,4)
b

tensor([[[0.4247, 0.9974, 0.8406, 0.0557],
         [0.0927, 0.9066, 0.0445, 0.8748],
         [0.9380, 0.4788, 0.1755, 0.4244]],

        [[0.5937, 0.8097, 0.7035, 0.6367],
         [0.9392, 0.4264, 0.1394, 0.1819],
         [0.7739, 0.4229, 0.7348, 0.2531]]])

In [9]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [15]:
#unsqueeze
c=torch.rand(226,226,3) #-> usually the size of a typical image
c

tensor([[[0.0704, 0.1647, 0.8116],
         [0.7444, 0.9435, 0.2132],
         [0.0493, 0.0313, 0.3381],
         ...,
         [0.3821, 0.0362, 0.6052],
         [0.5221, 0.8974, 0.4516],
         [0.6397, 0.8644, 0.0798]],

        [[0.2315, 0.9421, 0.5672],
         [0.3237, 0.0691, 0.6993],
         [0.7309, 0.1094, 0.0468],
         ...,
         [0.1097, 0.0692, 0.2201],
         [0.6341, 0.8896, 0.1101],
         [0.5597, 0.7243, 0.6777]],

        [[0.9274, 0.0383, 0.1541],
         [0.9983, 0.0801, 0.9045],
         [0.1923, 0.1526, 0.3555],
         ...,
         [0.7752, 0.3059, 0.7598],
         [0.5200, 0.3704, 0.5479],
         [0.1410, 0.8746, 0.5381]],

        ...,

        [[0.3493, 0.2498, 0.3184],
         [0.2300, 0.6275, 0.4300],
         [0.3931, 0.5324, 0.3715],
         ...,
         [0.4641, 0.5105, 0.2197],
         [0.8028, 0.0405, 0.7696],
         [0.5370, 0.3485, 0.3577]],

        [[0.5142, 0.0792, 0.0960],
         [0.2229, 0.1230, 0.5119],
         [0.

In [17]:
#unsqueeze
# c.unsqueeze(0).shape #-> adds a new dimension at 0 th position
c.unsqueeze(1).shape #-> adds a new dimension at 1st position

torch.Size([226, 1, 226, 3])

In [18]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and Pytorch:

In [19]:
import numpy as np

In [21]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [23]:
b=a.numpy()
b

array([1, 2, 3])

In [24]:
type(b)

numpy.ndarray

In [25]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [26]:
torch.from_numpy(c)

tensor([1, 2, 3])